version: 2

jobs:
  test:
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - run: make
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  test:
    jobs:
      - test